#!/usr/bin/env python3
"""
Turn role-instruction PDFs into the page images the secure viewer serves.

WHY THIS EXISTS
    The website must never hold the real PDF. This script renders each page of
    each PDF into a PNG and writes those PNGs, base64-encoded, into
    api/_lib/docs/. Vercel does not serve anything under api/ as a static file,
    so there is no URL anywhere on the site that returns the original document.

WHEN TO RUN IT
    Only when a role document changes, or when you are adding a new one.

HOW TO RUN IT
    py -m pip install pymupdf
    py tools/build-role-documents.py

ADDING A NEW DOCUMENT
    1. Put the PDF in the SOURCE folder below.
    2. Add a line to DOCUMENTS: (slug, filename, "Title as people should read it").
       The slug is what appears in the allowlist, so keep it lowercase-hyphenated.
    3. Run this script. It prints the exact lines to paste into
       api/_lib/allowlist.js and api/_lib/pages.js.
    4. Commit and push. Vercel redeploys and the document is live.
"""

import base64
import os

import pymupdf

# Where the PDFs live on your machine. Change this if you keep them elsewhere.
SOURCE = os.path.join(os.path.expanduser("~"), "Downloads")

# (slug, pdf filename, human-readable title)
DOCUMENTS = [
    ("project-manager",      "SOP-PM-01_Project_Manager.pdf",      "Project Manager — SOP-PM-01"),
    ("quantity-surveyor",    "SOP-QS-01_Quantity_Surveyor.pdf",    "Quantity Surveyor — SOP-QS-01"),
    ("procurement-officer",  "SOP-PR-01_Procurement_Officer.pdf",  "Procurement Officer — SOP-PR-01"),
    ("office-administrator", "SOP-OA-01_Office_Administrator.pdf", "Office Administrator — SOP-OA-01"),
]

# 150 DPI reads comfortably on screen without being a clean source for reprinting.
DPI = 150

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                       "api", "_lib", "docs")


def render(slug, filename, title):
    path = os.path.join(SOURCE, filename)
    if not os.path.exists(path):
        raise SystemExit("Cannot find %s\nPut it in %s, or edit SOURCE at the "
                         "top of this script." % (filename, SOURCE))

    doc = pymupdf.open(path)
    encoded = []
    for page in doc:
        pixmap = page.get_pixmap(dpi=DPI)
        encoded.append(base64.b64encode(pixmap.tobytes("png")).decode("ascii"))
    doc.close()

    body = ("// Generated by tools/build-role-documents.py from %s\n"
            "// Do not edit by hand. Re-run the script instead.\n"
            "module.exports = [\n%s\n];\n"
            % (filename, ",\n".join("  '%s'" % s for s in encoded)))

    target = os.path.normpath(os.path.join(OUT_DIR, slug + ".js"))
    with open(target, "w", encoding="ascii") as handle:
        handle.write(body)

    size_kb = round(os.path.getsize(target) / 1024)
    print("  %-22s %d pages  %5d KB" % (slug, len(encoded), size_kb))
    return len(encoded)


def main():
    os.makedirs(os.path.normpath(OUT_DIR), exist_ok=True)

    print("Rendering role documents at %d DPI:" % DPI)
    counts = {}
    for slug, filename, title in DOCUMENTS:
        counts[slug] = render(slug, filename, title)

    print("\nCheck that api/_lib/allowlist.js contains these entries in DOCUMENTS:")
    for slug, _filename, title in DOCUMENTS:
        print("  '%s':%s{ title: '%s', pages: %d },"
              % (slug, " " * max(1, 24 - len(slug)), title, counts[slug]))

    print("\nAnd that api/_lib/pages.js contains these loaders:")
    for slug, _filename, _title in DOCUMENTS:
        print("  '%s':%sfunction () { return require('./docs/%s'); },"
              % (slug, " " * max(1, 24 - len(slug)), slug))

    print("\nDone. Commit and push to publish.")


if __name__ == "__main__":
    main()
